---
- name: Configure AWS Instances for PHP
  hosts: aws
  become: true
  gather_facts: true

  tasks:
    - name: Update all packages to the latest version
      become: true
      apt:
        update_cache: yes
        upgrade: 'yes'
        autoremove: yes

    - name: Install PHP and necessary extensions
      become: true
      apt:
        name:
          - php
          - php-mysql
          - php-xml
          - php-fpm
          - php-cli
          - php-mbstring
          - php-gd
        state: latest
