---
- name: Install Node.js on Local VMs
  hosts: local_vms
  become: true
  tasks:
    - name: Install Node.js from Nodesource
      become: true
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
        apt-get install -y nodejs
      args:
        executable: /bin/bash

    - name: Verify Node.js installation
      command: node -v
      register: node_version
      changed_when: false

    - name: Show Node.js version
      debug:
        msg: "Node.js version installed - {{ node_version.stdout }}"
